server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    server_name _;
    client_max_body_size 100M;
    
    # Serve frontend static files
    root /var/www/todo-app;
    index index.html;
    
    # Frontend - SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
}
